(()=>{
'use strict';
const STORE='stella-baby-history-v3';
const FEED_KEYS=['feed1','feed2','feed3','feed4','dream'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const pad=n=>String(n).padStart(2,'0');
const dayKey=(d=new Date())=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const nowTime=()=>{const d=new Date();return `${pad(d.getHours())}:${pad(d.getMinutes())}`};
const fmt=t=>{if(!t)return '—';const [h,m]=t.split(':').map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const nativeGet=localStorage.getItem.bind(localStorage), nativeSet=localStorage.setItem.bind(localStorage);
const originalSetItem=Storage.prototype.setItem;
function read(){try{return JSON.parse(nativeGet(STORE)||'{}')}catch{return {days:{}}}}
function normalize(s){s=s&&typeof s==='object'?s:{};s.days=s.days||{};s.formulaUnit=s.formulaUnit||'oz';for(const d of Object.values(s.days)){d.actual=d.actual||{};d.formula=d.formula||{};d.manualEntries=Array.isArray(d.manualEntries)?d.manualEntries:[]}return s}
function toMl(amount,unit){amount=Number(amount);return Number.isFinite(amount)?(unit==='ml'?amount:amount*29.5735):null}
function fromMl(ml,unit){return unit==='ml'?ml:ml/29.5735}
function amountText(obj,preferred='oz'){if(!obj)return '—';const ml=Number(obj.ml??toMl(obj.amount,obj.unit||'oz'));if(!Number.isFinite(ml))return '—';const v=fromMl(ml,preferred);return preferred==='ml'?`${Math.round(v)} mL`:`${Math.round(v*10)/10} oz`}
function amountMl(obj){if(!obj)return 0;const ml=Number(obj.ml??toMl(obj.amount,obj.unit||'oz'));return Number.isFinite(ml)?ml:0}

// Preserve formula data whenever the core app rewrites localStorage.
Storage.prototype.setItem=function(key,value){
  if(this===localStorage&&key===STORE){
    try{
      const incoming=normalize(JSON.parse(value)),existing=normalize(JSON.parse(nativeGet(STORE)||'{}'));
      incoming.formulaUnit=existing.formulaUnit||incoming.formulaUnit||'oz';
      for(const [date,oldDay] of Object.entries(existing.days||{})){
        if(!incoming.days[date])continue;
        const next=incoming.days[date];next.formula=next.formula||{};
        for(const [k,v] of Object.entries(oldDay.formula||{}))if(next.actual?.[k])next.formula[k]=v;
        for(const k of Object.keys(next.formula))if(!next.actual?.[k])delete next.formula[k];
      }
      value=JSON.stringify(incoming);
    }catch{}
  }
  return originalSetItem.call(this,key,value);
};
function write(s){nativeSet(STORE,JSON.stringify(normalize(s)))}
function dayFor(s,key=dayKey(),create=true){s=normalize(s);if(!s.days[key]&&create)s.days[key]={anchors:{},actual:{},formula:{},manualEntries:[],resettles:[],lastChange:'',updatedAt:new Date().toISOString()};const d=s.days[key];if(d){d.actual=d.actual||{};d.formula=d.formula||{};d.manualEntries=Array.isArray(d.manualEntries)?d.manualEntries:[]}return d}
function manualFeeds(day){return (day?.manualEntries||[]).filter(e=>['feed','dream'].includes(e.type)&&amountMl(e.formula||e)>0)}
function scheduledFormula(day){return FEED_KEYS.filter(k=>day?.actual?.[k]&&amountMl(day.formula?.[k])>0).map(k=>({key:k,time:day.actual[k],formula:day.formula[k],label:k==='dream'?'Dream feed':`Feed ${k.replace('feed','')}`}))}
function dayFormula(day){const scheduled=scheduledFormula(day),manual=manualFeeds(day).map(e=>({key:e.id,time:e.time,formula:e.formula||e,label:e.type==='dream'?'Extra dream feed':'Extra feed',manual:true,note:e.note||''}));return [...scheduled,...manual].sort((a,b)=>(a.time||'').localeCompare(b.time||''))}
function totalMl(day){return dayFormula(day).reduce((n,e)=>n+amountMl(e.formula),0)}

function addStyles(){const s=document.createElement('style');s.textContent=`
.formulaCard{padding:15px;margin-top:10px}.formulaHead{display:flex;justify-content:space-between;align-items:flex-end;gap:12px}.formulaHead h3{margin:2px 0 0;font-size:1.15rem}.formulaTotal{text-align:right}.formulaTotal small{display:block;color:var(--muted);font-size:.62rem;font-weight:900;text-transform:uppercase;letter-spacing:.06em}.formulaTotal b{display:block;font-size:1.4rem;margin-top:2px}.formulaRows{margin-top:8px}.formulaRow{width:100%;display:grid;grid-template-columns:68px 30px 1fr auto;align-items:center;gap:8px;border:0;border-top:1px solid var(--line);background:transparent;padding:10px 0;text-align:left}.formulaRow:first-child{border-top:0}.formulaRow .ft{font-weight:900;font-size:.82rem}.formulaRow .fl b{display:block;font-size:.78rem}.formulaRow .fl small{display:block;color:var(--muted);font-size:.64rem;margin-top:2px}.formulaAmount{font-weight:950;font-size:.82rem}.formulaEmpty{color:var(--muted);font-size:.72rem;padding:9px 0 2px}.formulaAddMissing{color:var(--amber);font-size:.64rem;font-weight:900}.formulaQuickAmounts{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.formulaQuickAmounts button{border:1px solid var(--line);background:#fff;border-radius:999px;padding:7px 10px;font-weight:900;font-size:.72rem}.formulaDialogGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:12px}.formulaField{display:block;color:var(--muted);font-size:.7rem;font-weight:900}.formulaField input,.formulaField select{display:block;width:100%;margin-top:5px;border:1px solid var(--line);border-radius:11px;padding:9px;background:#fff;color:var(--ink);font:inherit;font-weight:900}.formulaStats{margin-top:9px;display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.formulaStat{background:#fffefa;border:1px solid var(--line);border-radius:17px;padding:12px}.formulaStat span{display:block;color:var(--muted);font-size:.61rem;text-transform:uppercase;letter-spacing:.06em;font-weight:900}.formulaStat b{display:block;font-size:1.15rem;margin-top:4px}.manualAmountWrap.hidden{display:none!important}
`;document.head.appendChild(s)}

let pendingKey=null, editingFormula=null;
function injectFeedDialog(){if($('#formulaDialog'))return;const dlg=document.createElement('dialog');dlg.id='formulaDialog';dlg.innerHTML=`<form method="dialog" class="dialogCard" id="formulaForm"><div class="dialogHead"><div><div class="eyebrow">Formula</div><h3 id="formulaTitle">Log feed</h3></div><button class="closeButton" value="cancel">×</button></div><p class="dialogHelp" id="formulaHelp">Log the bottle amount with the feed.</p><div class="formulaDialogGrid"><label class="formulaField">Time<input type="time" id="formulaTime" required></label><label class="formulaField">Amount<input type="number" id="formulaAmount" min="0" step="0.25" inputmode="decimal" placeholder="e.g. 6" required></label></div><div class="formulaQuickAmounts" id="formulaQuickAmounts"><button type="button" data-amt="4">4 oz</button><button type="button" data-amt="5">5 oz</button><button type="button" data-amt="6">6 oz</button><button type="button" data-amt="7">7 oz</button><button type="button" data-amt="8">8 oz</button></div><div class="dialogActions"><button type="button" class="secondary" id="formulaCancel">Cancel</button><button type="submit" class="primary">Save feed</button></div></form>`;document.body.appendChild(dlg);$('#formulaCancel').onclick=()=>dlg.close();$('#formulaQuickAmounts').onclick=e=>{const b=e.target.closest('[data-amt]');if(b)$('#formulaAmount').value=b.dataset.amt};$('#formulaForm').addEventListener('submit',e=>{e.preventDefault();saveScheduledFormula();dlg.close()})}
function openScheduled(key,label,time=nowTime(),existing=null){pendingKey=key;editingFormula=existing?key:null;const s=normalize(read()),unit=s.formulaUnit||'oz';$('#formulaTitle').textContent=existing?`Edit ${label}`:label;$('#formulaHelp').textContent=existing?'Update the amount for this bottle.':'This logs the feed time and how much formula she ate.';$('#formulaTime').value=time;const old=existing?dayFor(s)?.formula?.[key]:null;$('#formulaAmount').value=old?Math.round(fromMl(amountMl(old),unit)*100)/100:'';$('#formulaQuickAmounts').style.display=unit==='oz'?'flex':'none';$('#formulaDialog').showModal();setTimeout(()=>$('#formulaAmount').focus(),50)}
function saveScheduledFormula(){if(!pendingKey)return;const s=normalize(read()),d=dayFor(s),unit=s.formulaUnit||'oz',amount=Number($('#formulaAmount').value),time=$('#formulaTime').value||nowTime();if(!Number.isFinite(amount)||amount<=0)return;d.actual[pendingKey]=time;d.formula[pendingKey]={amount,unit,ml:toMl(amount,unit)};d.lastChange=`${pendingKey==='dream'?'Dream feed':pendingKey.replace('feed','Feed ')} logged at ${fmt(time)} · ${amountText(d.formula[pendingKey],unit)} formula.`;d.updatedAt=new Date().toISOString();write(s);location.reload()}
function nearestFeedKey(){const s=normalize(read()),d=dayFor(s),now=new Date().getHours()*60+new Date().getMinutes();if(d.actual?.dream)return null;if((d.actual?.bed||now>=20*60+30)&&!d.actual?.dream)return'dream';const rows=FEED_KEYS.slice(0,4).filter(k=>!d.actual?.[k]).map(k=>{const row=document.querySelector(`[data-edit="${k}"] .rowTime`);const t=row?.textContent?.trim();if(!t)return {k,delta:9999};const dt=new Date(`1/1/2000 ${t}`);return {k,delta:Math.abs(dt.getHours()*60+dt.getMinutes()-now)}}).sort((a,b)=>a.delta-b.delta);return rows[0]?.k||null}
function captureFeeds(){document.addEventListener('click',e=>{const feed=e.target.closest('#feedNowBtn');const hero=e.target.closest('#heroAction');let key=null,label='';if(feed){key=nearestFeedKey();label=key==='dream'?'Dream feed':key?key.replace('feed','Feed '):''}else if(hero&&FEED_KEYS.includes(hero.dataset.key)){key=hero.dataset.key;label=hero.dataset.label||key.replace('feed','Feed ')}if(!key)return;e.preventDefault();e.stopImmediatePropagation();openScheduled(key,label,nowTime(),false)},true)}

function injectCard(){if($('#formulaCard'))return;const after=$('#manualExtras')||$('.quickSection');if(!after)return;const card=document.createElement('section');card.id='formulaCard';card.className='card formulaCard';after.insertAdjacentElement('afterend',card);card.addEventListener('click',e=>{const b=e.target.closest('[data-formula-key]');if(!b)return;const s=normalize(read()),d=dayFor(s),key=b.dataset.formulaKey;openScheduled(key,key==='dream'?'Dream feed':key.replace('feed','Feed '),d.actual[key]||nowTime(),true)});renderCard()}
function renderCard(){const card=$('#formulaCard');if(!card)return;const s=normalize(read()),d=dayFor(s),unit=s.formulaUnit||'oz',items=dayFormula(d),scheduledMissing=FEED_KEYS.filter(k=>d.actual?.[k]&&!d.formula?.[k]);const total=totalMl(d);card.innerHTML=`<div class="formulaHead"><div><div class="eyebrow">Formula intake</div><h3>Today</h3></div><div class="formulaTotal"><small>Total</small><b>${total?amountText({ml:total},unit):'—'}</b></div></div><div class="formulaRows">${items.length?items.map(e=>`<${e.manual?'div':'button'} class="formulaRow" ${e.manual?'':`data-formula-key="${e.key}"`}><span class="ft">${fmt(e.time)}</span><span>🍼</span><span class="fl"><b>${esc(e.label)}</b>${e.note?`<small>${esc(e.note)}</small>`:''}</span><span class="formulaAmount">${amountText(e.formula,unit)}</span></${e.manual?'div':'button'}>`).join(''):'<div class="formulaEmpty">No formula amounts logged yet.</div>'}${scheduledMissing.map(k=>`<button class="formulaRow" data-formula-key="${k}"><span class="ft">${fmt(d.actual[k])}</span><span>🍼</span><span class="fl"><b>${k==='dream'?'Dream feed':k.replace('feed','Feed ')}</b><small class="formulaAddMissing">Tap to add amount</small></span><span class="formulaAmount">—</span></button>`).join('')}</div>`}

function enhanceManual(){const form=$('#manualEntryForm');if(!form||$('#manualAmountWrap'))return;const grid=form.querySelector('.manualDialogGrid');if(!grid)return;const wrap=document.createElement('label');wrap.id='manualAmountWrap';wrap.className='manualField manualAmountWrap';wrap.innerHTML='Formula amount (oz)<input type="number" id="manualFormulaAmount" min="0" step="0.25" inputmode="decimal" placeholder="e.g. 6">';grid.appendChild(wrap);const type=$('#manualEntryType');const toggle=()=>wrap.classList.toggle('hidden',!['feed','dream'].includes(type.value));type.addEventListener('change',toggle);toggle();let clickedId=null;document.addEventListener('click',e=>{const r=e.target.closest('[data-manual-id]');if(r){clickedId=r.dataset.manualId;setTimeout(()=>{const s=normalize(read());for(const d of Object.values(s.days)){const ent=(d.manualEntries||[]).find(x=>x.id===clickedId);if(ent){const unit=s.formulaUnit||'oz',ml=amountMl(ent.formula||ent);$('#manualFormulaAmount').value=ml?Math.round(fromMl(ml,unit)*100)/100:'';break}}toggle()},0)}else if(e.target.closest('#manualEntryBtn,#manualExtraAdd')){clickedId=null;setTimeout(()=>{$('#manualFormulaAmount').value='';toggle()},0)}},true);form.addEventListener('submit',()=>{const amount=Number($('#manualFormulaAmount').value),date=$('#manualEntryDate').value,typeVal=$('#manualEntryType').value,time=$('#manualEntryTime').value,note=$('#manualEntryNote').value;const id=clickedId;setTimeout(()=>{if(!['feed','dream'].includes(typeVal)||!Number.isFinite(amount)||amount<=0)return;const s=normalize(read()),d=dayFor(s,date,true),unit=s.formulaUnit||'oz';let ent=id?(d.manualEntries||[]).find(x=>x.id===id):null;if(!ent)ent=[...(d.manualEntries||[])].reverse().find(x=>x.type===typeVal&&x.time===time);if(ent){ent.formula={amount,unit,ml:toMl(amount,unit)};write(s);renderCard();decorateStats();decorateHistory()}},40)},true)}

function decorateHistory(){const s=normalize(read()),unit=s.formulaUnit||'oz';$$('[data-history]').forEach(card=>{if(card.querySelector('.formulaHistoryMetric'))return;const d=s.days?.[card.dataset.history],ml=totalMl(d);if(!ml)return;const metrics=card.querySelector('.historyMetrics');if(metrics)metrics.insertAdjacentHTML('beforeend',`<div class="historyMetric formulaHistoryMetric"><small>Formula</small><strong>${amountText({ml},unit)}</strong></div>`)});}
function rangeDays(s){const n=Number(s.statsRange||7),cut=new Date();cut.setHours(0,0,0,0);cut.setDate(cut.getDate()-(n-1));return Object.entries(s.days||{}).filter(([k])=>{const d=new Date(k+'T00:00:00');return d>=cut})}
function decorateStats(){const grid=$('#statGrid');if(!grid)return;const s=normalize(read()),unit=s.formulaUnit||'oz',days=rangeDays(s);const totals=days.map(([,d])=>totalMl(d)).filter(x=>x>0),bottles=days.flatMap(([,d])=>dayFormula(d).map(e=>amountMl(e.formula))).filter(x=>x>0);const avgDay=totals.length?totals.reduce((a,b)=>a+b,0)/totals.length:0,avgBottle=bottles.length?bottles.reduce((a,b)=>a+b,0)/bottles.length:0;const sig=[s.statsRange||7,Math.round(avgDay),Math.round(avgBottle),totals.length,bottles.length].join(':');const old=grid.querySelector('.formulaStatInjected');if(old?.dataset.sig===sig)return;grid.querySelectorAll('.formulaStatInjected').forEach(x=>x.remove());grid.insertAdjacentHTML('beforeend',`<div class="statCard formulaStatInjected" data-sig="${sig}"><span>Avg formula / day</span><b>${avgDay?amountText({ml:avgDay},unit):'—'}</b><small>${totals.length} day${totals.length===1?'':'s'} with amounts</small></div><div class="statCard formulaStatInjected" data-sig="${sig}"><span>Avg bottle</span><b>${avgBottle?amountText({ml:avgBottle},unit):'—'}</b><small>${bottles.length} bottle${bottles.length===1?'':'s'} logged</small></div>`)}
function observe(){const mo=new MutationObserver(()=>{renderCard();decorateHistory();decorateStats();enhanceManual()});['historyList','statGrid'].forEach(id=>{const n=document.getElementById(id);if(n)mo.observe(n,{childList:true,subtree:true})});$$('.tab').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{decorateHistory();decorateStats()},50)));$('#rangeTabs')?.addEventListener('click',()=>setTimeout(decorateStats,50))}
function init(){addStyles();injectFeedDialog();captureFeeds();injectCard();enhanceManual();decorateHistory();decorateStats();observe()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();